[package]
name = "lambdaworks-math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
thiserror = "1.0"
arbitrary = { version = "1", features = ["derive"], optional = true }

[features]
arbitrary = ["dep:arbitrary"]
