[package]
name = "lambdaworks-stark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
lambdaworks-math = { path = "../../math" }
lambdaworks-crypto = { path = "../../crypto"}
thiserror = "1.0.38"
uniffi = { version = "0.23.0" ,features = ["cli"]}

[build-dependencies]
uniffi = { version = "0.23.0", features = [ "build", "cli" ] }

[dev-dependencies]
uniffi = { version = "0.23.0", features = ["bindgen-tests", "cli"]}

[lib]
crate-type = ["lib", "cdylib"]
name = "lambdaworks_stark"

[[bin]]
name = "lambdaworks-stark"
path = "lambdaworks_stark.rs"
