[package]
name = "lambdaworks-prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.lambdaworks-math]
path = "../math"

[dependencies.lambdaworks-crypto]
path = "../crypto"

[dependencies]

[dev-dependencies]
parameterized_test = "0.2.1"