name: CI
on:
  push:
    branches: [cuda_fft_experimental]

jobs:
  test_cuda:
    name: Test CUDA
    runs-on: [self-hosted, cuda]
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Run tests
        run: cargo test -F cuda -- cuda
